name: sfy
channels:
  - conda-forge
dependencies:
  - pyyaml
  - pyserial
  - numpy
  - scipy
  - matplotlib
  - cartopy
  - pytz
  - requests
  - click
  - tabulate
  - tqdm
  - python-dotenv
  - coloredlogs
  - xarray
  - netcdf4
