name: sfy-data

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: sfytest
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
            profile: minimal

      - name: Install deps
        run: |
          sudo apt-get -y update
          sudo apt-get -y install build-essential libssl-dev

      - name: Build
        working-directory: sfy-data/
        run: cargo build --verbose

      - name: Test
        working-directory: sfy-data/
        run: cargo test --verbose

