name: sfy-buoy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  BUOYPR: test.product

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04

    steps:
      - name: Install deps
        run: |
          apt-get -y update
          apt-get -y install build-essential libssl-dev gcc-arm-none-eabi binutils-arm-none-eabi libclang-dev clang curl git

      - name: Work around git permission issue
        run: git config --global --add safe.directory /__w/sfy/sfy

      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Add rust target for thumbv7em
        run: |
          rustup default nightly
          rustup component add rust-src llvm-tools-preview rustc-dev
          rustup target add thumbv7em-none-eabihf

      - name: Build (buoy)
        working-directory: sfy-buoy/sfy-artemis
        run: cargo build --verbose

      - name: Test (host-tests)
        working-directory: sfy-buoy/
        run: make host-test

      - name: Build (target tests)
        working-directory: sfy-buoy/target-test
        run: cargo build --verbose --tests

