name: sfy-processing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      SFY_READ_TOKEN: ${{ secrets.SFY_READ_TOKEN }}
      SFY_SERVER: ${{ secrets.SFY_SERVER }}
      SFY_DATA_CACHE: /tmp/sfy
      CACHE_NUMBER: 2

    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v3
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
      id: cache

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        channels: conda-forge
        conda-remove-defaults: "true"
        channel-priority: true
        activate-environment: anaconda-client-env
        use-mamba: true
        environment-file: environment.yml

    - name: Test with pytest
      run: |
        cd sfy-processing/
        mamba install -y pytest pytest-benchmark
        pytest
