name: sfy-data

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
            profile: minimal

      - name: Install deps
        run: |
          sudo apt-get -y update
          sudo apt-get -y install build-essential libssl-dev

      - name: Build
        working-directory: sfy-data/
        run: cargo build --verbose

      - name: Test
        working-directory: sfy-data/
        run: cargo test --verbose

